# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ecaebe89ac28e830bd39c4798d97b39149cf51c6ac2623ec71ee23a9cdcd468b613580e17400b88cc1afcd285733a63bba6906139bad8d48c8e9f892cb0fdc1

test:
  secret_key_base: d19f141419c28d19c61aae01618d5399a0355bd3805958ffb84701d6aa52dfc89b72b37e37f93199e8abe61c1e8c0e8cc40e39c848dd1d49d147d613c7dfe4a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
